import api from "./api";

export const dataService = {
  getMentors: (params) => api.get("/mentors", { params }),
  getMentor: (id) => api.get(`/mentors/${id}`),
  getCategories: () => api.get("/categories"),
  getMyProfile: () => api.get("/users/profile"),
  updateProfile: (payload) => api.put("/users/profile", payload),
  toggleFavorite: (mentorId) => api.patch(`/users/favorites/${mentorId}`),
  getRequests: () => api.get("/requests"),
  createRequest: (payload) => api.post("/requests", payload),
  updateRequest: (id, payload) => api.patch(`/requests/${id}`, payload),
  getSessions: () => api.get("/sessions"),
  createSession: (payload) => api.post("/sessions", payload),
  updateSession: (id, payload) => api.patch(`/sessions/${id}`, payload),
  getGoals: () => api.get("/goals"),
  createGoal: (payload) => api.post("/goals", payload),
  updateGoal: (id, payload) => api.patch(`/goals/${id}`, payload),
  createConversation: (payload) => api.post("/conversations", payload),
  getConversations: (userId) => api.get(`/conversations/${userId}`),
  findConversation: (firstUserId, secondUserId) =>
    api.get(`/conversations/find/${firstUserId}/${secondUserId}`),
  getMessages: (conversationId) => api.get(`/messages/${conversationId}`),
  sendMessage: (payload) => api.post("/messages", payload),
  getNotifications: () => api.get("/notifications"),
  markNotificationRead: (id) => api.patch(`/notifications/${id}/read`),
  getReviews: (params) => api.get("/reviews", { params }),
  createReview: (payload) => api.post("/reviews", payload),
  mentorDashboard: () => api.get("/mentors/dashboard"),
  adminDashboard: () => api.get("/admin/dashboard"),
  adminUsers: () => api.get("/admin/users"),
  toggleBlockUser: (id) => api.patch(`/admin/users/${id}/toggle-block`),
  adminCategories: () => api.get("/admin/categories"),
  createCategory: (payload) => api.post("/admin/categories", payload),
  mentorApprovals: () => api.get("/admin/mentor-approvals"),
  approveMentor: (id) => api.patch(`/admin/mentor-approvals/${id}`),
};
